<a href="https://colab.research.google.com/github/rishike/machine_learning/blob/master/Handling_Date_and_Time_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [ ]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [ ]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [ ]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [ ]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

Working with Dates

In [ ]:
# converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [ ]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

Extract year

In [ ]:
date['date_year'] = date['date'].dt.year

date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

In [ ]:
date['date_month'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [ ]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

In [ ]:
date['date_day'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [ ]:
date['date_week'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [ ]:
date['date_dow_name'] = date['date'].dt.day_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_week,date_dow_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [ ]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1, 0)

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_week,date_dow_name,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

Extract week of the year

In [ ]:
dir(date['date'].dt)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__frozen',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_accessors',
 '_add_delegate_accessors',
 '_constructor',
 '_delegate_method',
 '_delegate_property_get',
 '_delegate_property_set',
 '_dir_additions',
 '_dir_deletions',
 '_freeze',
 '_get_values',
 '_hidden_attrs',
 '_parent',
 '_reset_cache',
 'as_unit',
 'ceil',
 'date',
 'day',
 'day_name',
 'day_of_week',
 'day_of_year',
 'dayofweek',
 'dayofyear',
 'days_in_month',
 'daysinmonth',
 'floor',
 'freq',
 'hour',
 'is_leap_year',
 'is_month_end',
 'is_month_start',
 'is_quarter_end',
 'is_quarter_start',
 'is_year_end',
 'is_year_start',
 'isocalendar',
 'microsecond',
 'minute',
 'month',
 'month_name',
 'nanosecond',
 'normalize',
 'quarter',
 'round',
 'second',
 'strftime',
 'time',
 'timetz',
 'to_period',
 'to_pydatetime',
 'tz',
 'tz_convert',
 'tz_localize',
 'unit',
 'weekday',
 'year']

In [ ]:
date['date_week_year'] = date['date'].dt.isocalendar().week

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_week,date_dow_name,date_is_weekend,date_week_year
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

extract quarter

In [ ]:
date['quarter'] = date['date'].dt.quarter

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_week,date_dow_name,date_is_weekend,date_week_year,quarter
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

In [ ]:
date['semester'] = np.where(date['quarter'].isin([1, 2]), 1 ,2)

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_week,date_dow_name,date_is_weekend,date_week_year,quarter,semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1

Extract time elapsed between dates

In [ ]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2025, 3, 28, 17, 30, 19, 532264)

In [ ]:
today - date['date']

0     1935 days 17:30:19.532264
1     2417 days 17:30:19.532264
2     2348 days 17:30:19.532264
3     2050 days 17:30:19.532264
4     2273 days 17:30:19.532264
                 ...
995   2363 days 17:30:19.532264
996   2304 days 17:30:19.532264
997   2152 days 17:30:19.532264
998   2217 days 17:30:19.532264
999   1991 days 17:30:19.532264
Name: date, Length: 1000, dtype: timedelta64[ns]

In [ ]:
(today - date['date']).dt.days

0      1935
1      2417
2      2348
3      2050
4      2273
       ...
995    2363
996    2304
997    2152
998    2217
999    1991
Name: date, Length: 1000, dtype: int64

In [ ]:
# Week passed

np.round((today - date['date']) /  np.timedelta64(1, 'W'), 0)

0      277.0
1      345.0
2      336.0
3      293.0
4      325.0
       ...
995    338.0
996    329.0
997    308.0
998    317.0
999    285.0
Name: date, Length: 1000, dtype: float64

In [ ]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [ ]:
time['date'] = pd.to_datetime(time['date'])

In [ ]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [ ]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [ ]:
# extract time part

time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [ ]:
# time difference

today - time['date']

0     4121 days 16:40:19.532264
1     3985 days 17:50:19.532264
2     4471 days 17:09:19.532264
3     3773 days 16:59:19.532264
4     4170 days 18:19:19.532264
                 ...
995   4760 days 16:40:19.532264
996   4081 days 18:16:19.532264
997   4546 days 17:53:19.532264
998   4662 days 17:56:19.532264
999   3934 days 18:05:19.532264
Name: date, Length: 1000, dtype: timedelta64[ns]

In [ ]:
# in seconds

(today - time['date']) / np.timedelta64(1, 's')

0      3.561144e+08
1      3.443682e+08
2      3.863562e+08
3      3.260484e+08
4      3.603540e+08
           ...
995    4.113240e+08
996    3.526642e+08
997    3.928388e+08
998    4.028614e+08
999    3.399627e+08
Name: date, Length: 1000, dtype: float64

In [ ]:
# in minute
(today - time['date']) / np.timedelta64(1, 'm')

0      5.935240e+06
1      5.739470e+06
2      6.439269e+06
3      5.434139e+06
4      6.005899e+06
           ...
995    6.855400e+06
996    5.877736e+06
997    6.547313e+06
998    6.714356e+06
999    5.666045e+06
Name: date, Length: 1000, dtype: float64